### ISSUE TITLE
function_samples

### ISSUE THREAD

**Issue by vdi-kakui** [vdi-kakui/gcloud#9]
# CloudFunction httpトリガーfunction作成
SDK環境回り含めてハンズオンしてみる。

https://cloud.google.com/functions/docs/quickstart-python?hl=ja

## 1. まずはCloudFunctionにする関数main.pyの作成

```functions/helloworld/main.py
from flask import escape

def hello_http(request):
    """HTTP Cloud Function.
    Args:
        request (flask.Request): The request object.
        <https://flask.palletsprojects.com/en/1.1.x/api/#incoming-request-data>
    Returns:
        The response text, or any set of values that can be turned into a
        Response object using `make_response`
        <https://flask.palletsprojects.com/en/1.1.x/api/#flask.make_response>.
    """
    request_json = request.get_json(silent=True)
    request_args = request.args

    if request_json and 'name' in request_json:
        name = request_json['name']
    elif request_args and 'name' in request_args:
        name = request_args['name']
    else:
        name = 'World'
    return 'Hello {}!'.format(escape(name))
```

## 2. ローカル環境から、main.pyをCloudFunctionにデプロイする。

```
#gcloud functions deploy (関数名) (ラインタイムにpython3.8を使用)
gcloud functions deploy hello_http --runtime python38 --trigger-http --allow-unauthenticated

#ログインの認証をしてから自動デプロイが行われる


#※つまづく場合は以下のアップデートコマンド入力
gcloud components update


```

## 3. 関数のテスト

関数がデプロイされたら、httpsTrigger.url プロパティをメモするか、次のコマンドを使用して検索します。

gcloud functions describe hello_http

次のようになります。

```
gcloud functions describe hello_http
availableMemoryMb: 256
buildId: 61712f79-f6d9-4092-b123-66508901e743
entryPoint: hello_http
httpsTrigger:
  securityLevel: SECURE_OPTIONAL
  url: https://us-central1-deep-freehold-265606.cloudfunctions.net/hello_http
ingressSettings: ALLOW_ALL
labels:
  deployment-tool: cli-gcloud
name: projects/deep-freehold-265606/locations/us-central1/functions/hello_http
runtime: python38
serviceAccountEmail: deep-freehold-265606@appspot.gserviceaccount.com
sourceUploadUrl: https://storage.googleapis.com/gcf-upload-us-central1-05942609-5955-45b2-a537-53558f7afe04/017d419f-52c3-4493-9ce2-42d11a5e27e8.zip?GoogleAccessId=service-7969177674@gcf-admin-robot.iam.gserviceaccount.com&Expires=1614424103&Signature=F3uACqLDBl06QMerSj9qCoL1FCmFe48CEwiw6kn%2BhtVR1s%2FdzseknN5epQg8nmKlCToWGOvzv7A2mEEWxz9U7O0TFoIArL8QJLO%2Fh0yFpFoFFXvrgaft%2Fi0EZXLrQe%2B19dbqVTnqXkers0R1v4EBcTy2bVCp3Y3%2Bi18Mxg3WzTDTHINrv5sbFHez4zFnKK1ZEghkxgJ6hU9fGHK2iZCfO81PJvTKCv%2F4CM0rXMpLei%2BxvzYIFOhhu472c79y6hXfx%2FW4f12FyfX7dZ698mVrojUJw1GwvL0XFGOScicUrX4HnPTb5RQ3EtZiB0JrIJMzmdgeeMB38SoERfqD%2BYIfRA%3D%3D
status: ACTIVE
timeout: 60s
updateTime: '2021-02-27T10:39:21.792Z'
versionId: '1'

```

https://GCP_REGION-PROJECT_ID.cloudfunctions.net/hello_http

ブラウザで、この URL にアクセスします。「Hello World!」というメッセージが表示されます。

たとえば、次の URL を使用して HTTP リクエストで名前を渡します。

https://GCP_REGION-PROJECT_ID.cloudfunctions.net/hello_http?name=NAME

「Hello NAME!」というメッセージが表示されます。

## 4. ログの表示

コマンドライン ツールの使用

Cloud Functions のログは、Cloud Logging UI または gcloud コマンドライン ツールで表示できます。

gcloud ツールを使用して関数のログを表示するには、logs read コマンドの後に関数の名前を続けます。

gcloud functions logs read hello_http
出力は次のようになります。

```
>gcloud functions logs read hello_http
LEVEL  NAME        EXECUTION_ID  TIME_UTC                 LOG
       hello_http                2021-02-27 10:39:21.748  [2021-02-27 10:39:21 +0000] [1] [INFO] Starting gunicorn 20.0.4
       hello_http                2021-02-27 10:39:21.749  [2021-02-27 10:39:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
       hello_http                2021-02-27 10:39:21.749  [2021-02-27 10:39:21 +0000] [1] [INFO] Using worker: threads
       hello_http                2021-02-27 10:39:21.783  [2021-02-27 10:39:21 +0000] [6] [INFO] Booting worker with pid: 6
D      hello_http  lm3ukdwx26ps  2021-02-27 11:02:04.837  Function execution started
       hello_http  lm3ukdwx26ps  2021-02-27 11:02:05.215  [2021-02-27 11:02:05 +0000] [1] [INFO] Starting gunicorn 20.0.4
       hello_http  lm3ukdwx26ps  2021-02-27 11:02:05.219  [2021-02-27 11:02:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
       hello_http  lm3ukdwx26ps  2021-02-27 11:02:05.219  [2021-02-27 11:02:05 +0000] [1] [INFO] Using worker: threads
       hello_http  lm3ukdwx26ps  2021-02-27 11:02:05.285  [2021-02-27 11:02:05 +0000] [6] [INFO] Booting worker with pid: 6
D      hello_http  lm3ukdwx26ps  2021-02-27 11:02:05.323  Function execution took 487 ms, finished with status code: 200
D      hello_http  q8e0t4xb3vkt  2021-02-27 11:24:29.522  Function execution started
       hello_http  q8e0t4xb3vkt  2021-02-27 11:24:30.031  [2021-02-27 11:24:30 +0000] [1] [INFO] Starting gunicorn 20.0.4
       hello_http  q8e0t4xb3vkt  2021-02-27 11:24:30.032  [2021-02-27 11:24:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
       hello_http  q8e0t4xb3vkt  2021-02-27 11:24:30.032  [2021-02-27 11:24:30 +0000] [1] [INFO] Using worker: threads
       hello_http  q8e0t4xb3vkt  2021-02-27 11:24:30.064  [2021-02-27 11:24:30 +0000] [6] [INFO] Booting worker with pid: 6
D      hello_http  q8e0t4xb3vkt  2021-02-27 11:24:30.140  Function execution took 619 ms, finished with status code: 200

```
---
---
## Google Cloud Storage トリガー

Storage でトリガーされる関数は、4 つのトリガータイプをサポートしています。これらのトリガータイプの値は、
関数をトリガーする Cloud Storage イベントを指定するために、関数のデプロイ時に使用されます。

google.storage.object.finalize（デフォルト）

google.storage.object.delete

google.storage.object.archive

google.storage.object.metadataUpdate

たとえば、以下の gcloud コマンドは、google.storage.object.finalize トリガータイプを使用して、指定された Cloud Storage バケットが書き込まれるたびに呼び出される関数をデプロイします。

オブジェクトのファイナライズ
トリガータイプの値: google.storage.object.finalize

このイベントは、バケット内で新しいオブジェクトが作成された時点（または既存のオブジェクトが上書きされ、そのオブジェクトの新しい世代が作成された時点）で送信されます。

## 次の関数は、イベントの発生時に関連データをログに記録します。

functions/helloworld/main.py

```main.py
def hello_gcs(event, context):
    """Background Cloud Function to be triggered by Cloud Storage.
       This generic function logs relevant data when a file is changed.

    Args:
        event (dict):  The dictionary with data specific to this type of event.
                       The `data` field contains a description of the event in
                       the Cloud Storage `object` format described here:
                       https://cloud.google.com/storage/docs/json_api/v1/objects#resource
        context (google.cloud.functions.Context): Metadata of triggering event.
    Returns:
        None; the output is written to Stackdriver Logging
    """

    print('Event ID: {}'.format(context.event_id))
    print('Event type: {}'.format(context.event_type))
    print('Bucket: {}'.format(event['bucket']))
    print('File: {}'.format(event['name']))
    print('Metageneration: {}'.format(event['metageneration']))
    print('Created: {}'.format(event['timeCreated']))
    print('Updated: {}'.format(event['updated']))
```

## 関数のデプロイ
オブジェクト ファイナライズ トリガーで関数をデプロイするには、関数コードのあるディレクトリで次のコマンドを実行します。
（）バケットトリガーにするためオプション「 --trigger-resource YOUR_TRIGGER_BUCKET_NAME」「 --trigger-event google.storage.object.finalize」が必要になります。

```
# Python

gcloud functions deploy hello_gcs --runtime python38 --trigger-resource YOUR_TRIGGER_BUCKET_NAME --trigger-event google.storage.object.finalize
```

```
# Python

gcloud functions deploy hello_gcs --runtime python38 --trigger-resource function20210227 --trigger-event google.storage.object.finalize

asia-northeast1
```

## ログの確認

バケットへのファイルのアップロード・デリートがログとして記録されるのを確認できる。

参考：
https://cloud.google.com/functions/docs/calling/storage?hl=ja
---
---
# Cloud Pub/Sub のチュートリアル

HTTP トリガー関数を使用して Pub/Sub push サブスクリプションをリッスンできます。
HTTP 関数を使用すれば、1 つの関数で複数の Pub/Sub トピックに登録できます。

## 予定作成物

Pub/Sub トピックにメッセージを公開して関数をトリガーする。
メッセージ送信時にfunctionが起動しhello world + メッセージが送信されfunctionログに記録される。

## 初期設定
Cloud Functions and Cloud Pub/Sub API を有効にします。
API を有効にする

Cloud SDK をインストールして初期化します。
Cloud SDK がすでにインストールされている場合は、次のコマンドを実行して更新します。

gcloud components update

## 1. 関数の作成
pubsubトリガーの関数を作成します。

```main.py
def hello_pubsub(event, context):
    """Background Cloud Function to be triggered by Pub/Sub.
    Args:
         event (dict):  The dictionary with data specific to this type of
         event. The `data` field contains the PubsubMessage message. The
         `attributes` field will contain custom attributes if there are any.
         context (google.cloud.functions.Context): The Cloud Functions event
         metadata. The `event_id` field contains the Pub/Sub message ID. The
         `timestamp` field contains the publish time.
    """
    import base64

    print("""This Function was triggered by messageId {} published at {}
    """.format(context.event_id, context.timestamp))

    if 'data' in event:
        name = base64.b64decode(event['data']).decode('utf-8')
    else:
        name = 'World'
    print('Hello {}!'.format(name))

```

## 2. 関数のデプロイ

```
gcloud functions deploy hello_pubsub --runtime python38 --trigger-topic YOUR_TOPIC_NAME

gcloud functions deploy hello_pubsub --runtime python38 --trigger-topic topic
```

## 3.トピックの作成
※pubsubトピックが存在しない場合は以下のコマンドで作成します。

```
gcloud pubsub topics create トピック名
Created topic [projects/プロジェクト名/topics/トピック名].
```

## 4. Pub/Subメッセージ送信

1. メッセージを Pub/Sub トピックに公開します。この例では、メッセージは関数が挨拶に含める名前です。

```
gcloud pubsub topics publish YOUR_TOPIC_NAME --message YOUR_NAME
#YOUR_TOPIC_NAME を Pub/Sub トピックの名前に置き換え、YOUR_NAME を任意の文字列に置き換えます。
```

## 5. ログの表示

gcloud functions logs read hello_pubsub --limit 50
出力は次のようになります。

## クリーンアップ

gcloud functions delete hello_pubsub

[参考]
Cloud Pub/Sub のチュートリアル
https://cloud.google.com/functions/docs/tutorials/pubsub?hl=ja

Google Cloud Pub/Sub トリガー
https://cloud.google.com/functions/docs/calling/pubsub?hl=ja

---
---

## 関数内からメッセージを公開する

関数内からメッセージを Pub/Sub トピックに公開することもできます。
https://cloud.google.com/functions/docs/calling/pubsub?hl=ja#publishing_a_message_from_within_a_function
